-- RSVP table for the wedding site.
-- Run this in Supabase → SQL Editor once (or when updating the schema).
--
-- Design: ONE record per guest. guest_id is UNIQUE, so re-submitting the RSVP
-- REPLACES the existing row (the /api/rsvp endpoint upserts on guest_id).

create table if not exists public.rsvps (
  id            bigint generated by default as identity primary key,
  guest_id      text unique not null,     -- guest code (?g=CODE) or "phone:<digits>" fallback
  name          text not null,            -- full / real name (from guests.js fullName)
  display_name  text,                     -- display nickname shown in the greeting
  phone         text not null,
  attending     text not null,            -- 'yes' | 'no'
  adults        int  not null default 0,
  children      int  not null default 0,
  pickup        text default '',          -- '' | 'tlv_after' | 'tlv_noafter'
  notes         text default '',
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);

-- If the table already existed from an earlier version, add the new columns:
alter table public.rsvps add column if not exists display_name text;
alter table public.rsvps add column if not exists updated_at   timestamptz not null default now();

-- Ensure guest_id is unique so upsert (on_conflict=guest_id) works as a replace.
-- (Safe to run repeatedly.)
do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'rsvps_guest_id_key'
  ) then
    alter table public.rsvps add constraint rsvps_guest_id_key unique (guest_id);
  end if;
end $$;
