#!/usr/bin/env node
// Recent-status list: for every guest, their MOST RELEVANT delivery status.
//
// "Save all data, show the most relevant status" — the webhook keeps every
// status row; this reconstructs each guest's current standing (a later
// successful resend overrides an earlier failure) and writes STATUS.md.
//
// It reads the live /api/delivery endpoint (raw mode) and applies the same
// summarize logic locally, so it stays correct even if the deployed summary
// endpoint is stale. Manual sends (outside our sender) come from
// status-overrides.json.
//
// Usage:
//   WEDDING_SUMMARY_KEY=... node scripts/status.js            # write STATUS.md + print
//   node scripts/status.js --key=... [--base=https://dvichal-wedding.com]

import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { GUESTS } from '../src/guests.js';
import { summarizeDelivery } from '../api/delivery.js';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '..');

const flags = {};
for (const a of process.argv.slice(2)) {
  if (a.startsWith('--')) { const [k, v] = a.slice(2).split('='); flags[k] = v === undefined ? true : v; }
}
const KEY = flags.key || process.env.WEDDING_SUMMARY_KEY;
const BASE = flags.base || 'https://dvichal-wedding.com';
if (!KEY) { console.error('Need a summary key: --key=... or WEDDING_SUMMARY_KEY=...'); process.exit(1); }

function toE164(phone) {
  const p = String(phone).trim();
  if (p.startsWith('+')) return p.slice(1).replace(/\D/g, '');
  const digits = p.replace(/\D/g, '');
  if (digits.startsWith('0')) return '972' + digits.slice(1);
  return digits;
}

async function getJSON(url) {
  const r = await fetch(url);
  if (!r.ok) throw new Error(`${url} → HTTP ${r.status}`);
  return r.json();
}

function loadOverrides() {
  const p = join(ROOT, 'status-overrides.json');
  if (!existsSync(p)) return {};
  try {
    const o = JSON.parse(readFileSync(p, 'utf8'));
    delete o._comment;
    return o;
  } catch { return {}; }
}

async function main() {
  // 1. Which numbers have any webhook activity.
  const summary = await getJSON(`${BASE}/api/delivery?key=${encodeURIComponent(KEY)}`);
  const phones = summary.guests.map((g) => g.phone);

  // 2. Pull the raw per-message timeline for those numbers and recompute
  //    locally (correct even when the deployed summary is stale).
  const raw = await getJSON(`${BASE}/api/delivery?key=${encodeURIComponent(KEY)}&raw=1&phones=${phones.join(',')}`);
  const rows = raw.events.map((e) => ({
    wa_message_id: e.wamid, recipient_phone: e.phone, status: e.status,
    error_code: e.error ? e.error.split(' ')[0] : null,
    error_title: e.error ? e.error.split(' ').slice(1).join(' ') : null,
    at: e.at,
  }));
  const computed = summarizeDelivery(rows);
  const byPhone = {};
  for (const g of computed.guests) byPhone[g.phone] = g;

  // 3. Merge with the full guest list + manual overrides.
  const overrides = loadOverrides();
  const codeByPhone = {};
  for (const [code, g] of Object.entries(GUESTS)) codeByPhone[toE164(g.phone)] = code;

  const list = [];
  for (const [code, g] of Object.entries(GUESTS)) {
    if (code === 'testMichal') continue;
    const phone = toE164(g.phone);
    const ov = overrides[code];
    const web = byPhone[phone];
    let status, error = null, note = null, at = null;
    if (ov) { status = ov.status; note = ov.note; at = web?.at || null; }
    else if (web) { status = web.status; error = web.error; at = web.at; }
    else { status = 'not-sent'; }
    list.push({ code, name: g.name, fullName: g.fullName, phone: '+' + phone, status, error, note, at });
  }

  // 4. Group + write.
  const ORDER = ['read', 'delivered', 'sent', 'failed', 'not-sent'];
  const rank = (s) => { const i = ORDER.indexOf(s); return i < 0 ? 99 : i; };
  list.sort((a, b) => rank(a.status) - rank(b.status) || a.name.localeCompare(b.name));

  const counts = {};
  for (const g of list) counts[g.status] = (counts[g.status] || 0) + 1;

  const lines = [];
  lines.push('# Delivery status — recent status per guest');
  lines.push('');
  lines.push('_Most-relevant status per guest: a later successful resend overrides an earlier failure._');
  lines.push('_Generated by `node scripts/status.js`. Manual sends come from status-overrides.json._');
  lines.push('');
  lines.push('**Totals:** ' + ORDER.filter((s) => counts[s]).map((s) => `${s}: ${counts[s]}`).join(' · '));
  lines.push('');
  for (const s of ORDER) {
    const g = list.filter((x) => x.status === s);
    if (!g.length) continue;
    lines.push(`## ${s} (${g.length})`);
    for (const x of g) {
      const extra = x.note ? ` — _${x.note}_` : (x.error ? ` — ${x.error}` : '');
      const full = x.fullName && x.fullName !== x.name ? ` — ${x.fullName}` : '';
      lines.push(`- ${x.name}${full} (${x.phone})${extra}`);
    }
    lines.push('');
  }
  const out = lines.join('\n');
  writeFileSync(join(ROOT, 'STATUS.md'), out + '\n');
  console.log(out);
  console.log('\nWrote STATUS.md');
}

main().catch((e) => { console.error(e); process.exit(1); });
