const GUESTS = {
  // --- Michal's family ---
  NikolAndJulian: { name: 'Nikol & Julian', fullName: 'Nikol Wolpert', phone: '+19296225141', lang: 'en', form: 'plural' },
  ViktoriaSharay: { name: 'Мамик и Папик', fullName: 'Viktoria Sharay', phone: '0504247004', lang: 'ru', form: 'plural' },
  LarisaSharay: { name: 'Лялик', fullName: 'Larisa Sharay', phone: '0544575308', lang: 'ru', form: 'f' },
  OlegSharay: { name: 'Олешака', fullName: 'Oleg Sharay', phone: '0503421703', lang: 'ru', form: 'm' },
  Olga: { name: 'Olga, Deerk, Lara, Yana and Masha', fullName: 'Olga Beloborodova', phone: '+32474520752', lang: 'en', form: 'plural' },

  // --- Friends ---
  OfirLevin: { name: 'אופיר ויונתן', fullName: 'אופיר לוין', phone: '0546644905', lang: 'he', form: 'plural' },
  DvirSasson: { name: 'דביר', fullName: 'דביר ששון', phone: '0502566643', lang: 'he', form: 'm' },
  DanKedmi: { name: 'אלי', fullName: 'דן קדמי', phone: '0509878804', lang: 'he', form: 'm' },
  LiorMandelboim: { name: 'ליאור ויונתן', fullName: 'ליאור מנדלבוים', phone: '0546213030', lang: 'he', form: 'plural' },
  RotemAgmon: { name: 'רתמי וגיא', fullName: 'רתם אגמון', phone: '0544317502', lang: 'he', form: 'plural' },
  RonDeitch: { name: 'רון והדר', fullName: 'רון דיטש', phone: '0547911403', lang: 'he', form: 'plural' },
  RonWolpert: { name: 'רון המתוק', fullName: 'רון וולפרט', phone: '0526998033', lang: 'he', form: 'm' },
  AlinaDronov: { name: 'אלינקי', fullName: 'אלינה דרונוב', phone: '0545488475', lang: 'he', form: 'f' },
  YuvalGoldstein: { name: 'יוב', fullName: 'יובל גולדשטיין', phone: '0547090583', lang: 'he', form: 'f' },
  RomiHeller: { name: 'רומאמי', fullName: 'רומי הלר', phone: '0547981025', lang: 'he', form: 'f' },
  MaorPeretz: { name: 'מאורי', fullName: 'Maor Peretz', phone: '0542899187', lang: 'he', form: 'm' },
  YotamSuliman: { name: 'יות וגיל', fullName: 'יותם סולימן', phone: '0504600888', lang: 'he', form: 'plural' },
  RonnyAndGuy: { name: 'רוני וגיא', fullName: 'רוני גודורוב', phone: '0546826789', lang: 'he', form: 'plural' },
  SigalSasson: { name: 'סיגל ואייל', fullName: 'Sigal Sasson', phone: '0547949355', lang: 'he', form: 'plural' },
  ItaySasson: { name: 'איתי ועמיר', fullName: 'Itay Sasson', phone: '0535301805', lang: 'he', form: 'plural' },
  ShellyReizis: { name: 'שלי', fullName: 'Shelly Reizis', phone: '0527027829', lang: 'he', form: 'f' },
  MichaelYafe: { name: 'מיכאל', fullName: 'מיכאל יפה', phone: '0526462911', lang: 'he', form: 'm' },
  OmriAmit: { name: 'עומרי', fullName: 'Omri Amit', phone: '0545655099', lang: 'he', form: 'plural' },

  // --- test entry ---
  testMichal: { name: 'מיכלי', fullName: 'Michal (test)', phone: '0507155207', lang: 'he', form: 'f' },

  // --- Michal's work friends ---
  MorFilo: { name: 'מור ותומר', fullName: 'מור פילו', phone: '0506863116', lang: 'he', form: 'plural' },
  OrrBinyamini: { name: 'אור', fullName: 'אור בנימיני', phone: '0509349101', lang: 'he', form: 'm' },
  MorBenAmi: { name: 'מור', fullName: 'מור בן עמי', phone: '0549439445', lang: 'he', form: 'f' },
  ThaiHayut: { name: 'תאי', fullName: 'תאי חיות', phone: '0542604840', lang: 'he', form: 'f' },

  // --- Michal's family (Russian-speaking) ---
  StasaGetelman: { name: 'Стыся и Сеня', fullName: 'Stasa Getelman', phone: '0505683789', lang: 'ru', form: 'plural' },
  OlgaAltshul: { name: 'Оля и Боря', fullName: 'Olga Altshul', phone: '0544951380', lang: 'ru', form: 'plural' },
  MarinaAgizin: { name: 'Марина', fullName: 'Marina Agizin', phone: '0528895280', lang: 'ru', form: 'f' },
  Asia: { name: 'Ася', fullName: 'Asia', phone: '+491766387721', lang: 'ru', form: 'f' },
  LaraShapiro: { name: 'Лара и Боря', fullName: 'Lara Shapiro', phone: '+15854730464', lang: 'ru', form: 'plural' },
  LarisaKanevski: { name: 'Лариса', fullName: 'Larisa Kanevski', phone: '+14165006516', lang: 'ru', form: 'f' },
  RayaTrahtenberg: { name: 'Рая и Леня', fullName: 'Raya Trahtenberg', phone: '+79859502386', lang: 'ru', form: 'plural' },
  MichaelMatushevski: { name: 'Миша и Лариса', fullName: 'Michael Matushevski', phone: '0507228134', lang: 'ru', form: 'plural' },
  MarinaMihnevich: { name: 'Марина и Паша', fullName: 'Marina Mihnevich', phone: '0539858980', lang: 'ru', form: 'plural' },
  GlebMihnevich: { name: 'Таня и Глеб', fullName: 'Gleb Mihnevich', phone: '0533801970', lang: 'ru', form: 'plural' },
  NataliaPozdnuhova: { name: 'Наташа', fullName: 'Natalia Pozdnuhova', phone: '0532583539', lang: 'ru', form: 'f' },
  AlexAshvind: { name: 'Алеша', fullName: 'Alex Ashvind', phone: '0533802004', lang: 'ru', form: 'm' },
  LeonidPozdnuhov: { name: 'Леня и Наташа', fullName: 'Leonid Pozdnuhov', phone: '0533784580', lang: 'ru', form: 'plural' },
  SoniaLevin: { name: 'Соня и Боб', fullName: 'Sonia Levin', phone: '0525322523', lang: 'ru', form: 'plural' },
  AnnaNahmanson: { name: 'Аня', fullName: 'Anna Nahmanson', phone: '+79213149495', lang: 'ru', form: 'f' },
  IlyaNahmanson: { name: 'Илья', fullName: 'Ilya Nahmanson', phone: '+79119763699', lang: 'ru', form: 'm' },
  AnnaRudoy: { name: 'Аня и Саша', fullName: 'Anna Rudoy', phone: '0545749947', lang: 'ru', form: 'plural' },
  SashaZalzman: { name: 'Саша', fullName: 'Sasha Zalzman', phone: '0547326031', lang: 'ru', form: 'm' },
  SimonIkirson: { name: 'Сема и Лена', fullName: 'Simon Ikirson', phone: '0535272556', lang: 'ru', form: 'plural' },
  JuliaSharay: { name: 'Юля и Сева', fullName: 'Julia Sharay', phone: '+79162212070', lang: 'ru', form: 'plural' },
  BochkoLena: { name: 'Алена и Боря', fullName: 'Lena Bochko', phone: '+19087397619', lang: 'ru', form: 'plural' },
  AlexanderUnger: { name: 'Шулим', fullName: 'Alexander Unger', phone: '+4917684384736', lang: 'ru', form: 'm' },

  // --- Michal's family (Hebrew-speaking) ---
  ValeriaRejabek: { name: 'לרה', fullName: 'Valeria Rejabek', phone: '0524548984', lang: 'he', form: 'f' },
  AlexRejabek: { name: 'סשה ושחר', fullName: 'Alex Rejabek', phone: '0509250099', lang: 'he', form: 'plural' },
  MichaelRejabek: { name: 'מיכאל וריקי', fullName: 'Michael Rejabek', phone: '0525582965', lang: 'he', form: 'plural' },
  DanialRejabek: { name: 'דניאל ורוני', fullName: 'Danial Rejabek', phone: '0524548987', lang: 'he', form: 'plural' },
  Max: { name: 'מקסים', fullName: 'Max', phone: '0545500494', lang: 'he', form: 'm' },
  NinaTravizki: { name: 'נינה וארסניי', fullName: 'Nina Travizki', phone: '0544782618', lang: 'he', form: 'plural' },
  IdanTravizki: { name: 'עידן', fullName: 'Idan Travizki', phone: '0587046540', lang: 'he', form: 'm' },
  AnnaVolpert: { name: 'אניה', fullName: 'Anna Volpert', phone: '0547957960', lang: 'he', form: 'f' },
  DavidVolpert: { name: 'דויד ויוליה', fullName: 'David Volpert', phone: '0546201209', lang: 'he', form: 'plural' },
  DinaVolpert: { name: 'דינה', fullName: 'Dina Volpert', phone: '0546446177', lang: 'he', form: 'f' },
  HadasaVolpert: { name: 'הדסה', fullName: 'Hadasa Volpert', phone: '0526232211', lang: 'he', form: 'f' },
  RitaReizis: { name: 'ריטה וולרה', fullName: 'Rita Reizis', phone: '0545305278', lang: 'he', form: 'plural' },
  NataliVidro: { name: 'נטשה ואליה', fullName: 'Natali Vidro', phone: '0544917892', lang: 'he', form: 'plural' },
  LenaZilberg: { name: 'לנה ופבל', fullName: 'Lena Zilberg', phone: '0544933625', lang: 'he', form: 'plural' },
  OlgaUchitel: { name: 'אוליה וזוריק', fullName: 'Olga Uchitel', phone: '0546090427', lang: 'he', form: 'plural' },
  MarinaMarkovich: { name: 'מרינה ואדיק', fullName: 'Marina Markovich', phone: '0525111211', lang: 'he', form: 'plural' },
  FelixLebed: { name: 'ג׳ניה ופליקס', fullName: 'Felix Lebed', phone: '0545402019', lang: 'he', form: 'plural' },
  MarinaAristova: { name: 'מרינה', fullName: 'Marina Aristova', phone: '0543053965', lang: 'he', form: 'f' },
  YuvalBinder: { name: 'מוניקה ויובל', fullName: 'Yuval Binder', phone: '0508805192', lang: 'he', form: 'plural' },
  BorisFlasburg: { name: 'בוריס', fullName: 'Boris Flasburg', phone: '0546308417', lang: 'he', form: 'm' },
  AnnaDainov: { name: 'אניה ומישה', fullName: 'Anna Dainov', phone: '0528915534', lang: 'he', form: 'plural' },
  KaterinaEpshtein: { name: 'קטיה וולרה', fullName: 'Katerina Epshtein', phone: '0522406687', lang: 'he', form: 'plural' },
  SofiaNeznatni: { name: 'סופה', fullName: 'Sofia Neznatni', phone: '0507755737', lang: 'he', form: 'f' },
  LenaFatale: { name: 'לנה וג׳ניה', fullName: 'Lena Fatale', phone: '0544605466', lang: 'he', form: 'plural' },
  AlexSinelnikov: { name: 'סשה וסטלה', fullName: 'Alex Sinelnikov', phone: '0525440371', lang: 'he', form: 'plural' },
  LeonidPraisman: { name: 'ליאוניד ואלה', fullName: 'Leonid Praisman', phone: '0547544457', lang: 'he', form: 'plural' },
  VladimirBrodski: { name: 'ולדימיר', fullName: 'Vladimir Brodski', phone: '0507521570', lang: 'he', form: 'm' },
  LiorMitna: { name: 'ליאור', fullName: 'Lior Mitna', phone: '0506861846', lang: 'he', form: 'm' },
  AlonWegman: { name: 'אלון', fullName: 'Alon Wegman', phone: '0542558880', lang: 'he', form: 'm' },
  NadavSolomon: { name: 'נדב', fullName: 'Nadav Solomon', phone: '0547878838', lang: 'he', form: 'm' },
  RonMorgulis: { name: 'רון', fullName: 'Ron Morgulis', phone: '0545593238', lang: 'he', form: 'm' },
  AdamKira: { name: 'אדם', fullName: 'Adam Kira', phone: '0503566515', lang: 'he', form: 'm' },
  IdoEizer: { name: 'עידו', fullName: 'Ido Eizer', phone: '0587966566', lang: 'he', form: 'm' },
  EranGroovman: { name: 'ערן', fullName: 'Eran Groovman', phone: '0537214567', lang: 'he', form: 'm' },
  YovalCipele: { name: 'יובל', fullName: 'Yoval Cipele', phone: '0533345430', lang: 'he', form: 'm' },
  IlayShtern: { name: 'עילי', fullName: 'Ilay Shtern', phone: '+13074137595', lang: 'he', form: 'm' },

  // --- Michal's wider circle (from contacts) ---
  LiorMizrahi: { name: 'ליאור ושירה', fullName: 'Lior Mizrahi', phone: '0546880090', lang: 'he', form: 'plural' },
  NirElishoov: { name: 'אלישוב', fullName: 'Nir Elishoov', phone: '0502057263', lang: 'he', form: 'm' },
  OfekAharoni: { name: 'אופק', fullName: 'Ofek Aharoni', phone: '0507738440', lang: 'he', form: 'm' },
  IdoEhrlich: { name: 'ארליך', fullName: 'Ido Ehrlich', phone: '0543153883', lang: 'he', form: 'm' },
  AmitGazal: { name: 'גזאל', fullName: 'Amit Gazal', phone: '0526770624', lang: 'he', form: 'm' },
  GuyHanin: { name: 'חנין', fullName: 'Guy Hanin', phone: '0502848540', lang: 'he', form: 'm' },
  GalVaisvaser: { name: 'וייס', fullName: 'Gal Vaisvaser', phone: '0506386081', lang: 'he', form: 'm' },
  YuvalZabatani: { name: 'זבי', fullName: 'Yuval Zabatani', phone: '0507627594', lang: 'he', form: 'm' },
  RoiLevartovski: { name: 'לברה', fullName: 'Roi Levartovski', phone: '0522421480', lang: 'he', form: 'm' },
  MatanPorat: { name: 'מתן', fullName: 'Matan Porat', phone: '0524686836', lang: 'he', form: 'm' },
  NitaiWeil: { name: 'נתאי', fullName: 'Nitai Weil', phone: '0548363235', lang: 'he', form: 'm' },
  IvriKarni: { name: 'עבריקו', fullName: 'Ivri Karni', phone: '0526499698', lang: 'he', form: 'm' },
  OrFranco: { name: 'פרנקו ומיכל', fullName: 'Or Franco', phone: '0503013354', lang: 'he', form: 'plural' },
  RonSade: { name: 'רון', fullName: 'Ron Sade', phone: '0543318451', lang: 'he', form: 'm' },
  IdoSchwarz: { name: 'שוורצי', fullName: 'Ido Schwarz', phone: '0547977992', lang: 'he', form: 'm' },
  TomShlaim: { name: 'תומאס', fullName: 'Tom Shlaim', phone: '0526204304', lang: 'he', form: 'm' },
  AmitCarmi: { name: 'כרמי', fullName: 'Amit Carmi', phone: '0502182030', lang: 'he', form: 'm' },
  DanaNir: { name: 'דנה ועומר', fullName: 'Dana Nir', phone: '0503310197', lang: 'he', form: 'plural' },
  NirChachamoviz: { name: 'ניר וליאור', fullName: 'Nir Chachamoviz', phone: '0547537723', lang: 'he', form: 'plural' },
  TomCohen: { name: 'תום ושלי', fullName: 'Tom Cohen', phone: '0525677400', lang: 'he', form: 'plural' },
  GalBergman: { name: 'ברגי', fullName: 'Gal Bergman', phone: '0544227569', lang: 'he', form: 'm' },
  AmitKeren: { name: 'עמית ושינייד', fullName: 'Amit Keren', phone: '0502526995', lang: 'he', form: 'plural' },
  StavToledo: { name: 'סתיו וסופיה', fullName: 'Stav Toledo', phone: '0502636169', lang: 'he', form: 'plural' },
  MorKariti: { name: 'מור ומאיה', fullName: 'Mor Kariti', phone: '0542773737', lang: 'he', form: 'plural' },
  MaorDavid: { name: 'מאור ונועם', fullName: 'Maor David', phone: '0507773656', lang: 'he', form: 'plural' },
  DanaAnavi: { name: 'דנבי', fullName: 'Dana Anavi', phone: '0528287241', lang: 'he', form: 'f' },
  HalelGabber: { name: 'הלל', fullName: 'Halel Gabber', phone: '+61474802025', lang: 'he', form: 'f' },
  KerenRozen: { name: 'קרן', fullName: 'Keren Rozen', phone: '0547731003', lang: 'he', form: 'f' },
  NoamHayu: { name: 'נעם ודור', fullName: 'Noam Hayu', phone: '0524227909', lang: 'he', form: 'plural' },
  AdiPeres: { name: 'עדי', fullName: 'Adi Peres', phone: '0507108101', lang: 'he', form: 'f' },
  YuvalSossover: { name: 'סוסו ועמוס', fullName: 'Yuval Sossover', phone: '0545613304', lang: 'he', form: 'plural' },
  DrorPeretz: { name: 'דרוריטוס והודיה', fullName: 'Dror Peretz', phone: '0544670655', lang: 'he', form: 'plural' },
  YaelGilad: { name: 'יעל', fullName: 'Yael Gilad', phone: '0542130006', lang: 'he', form: 'f' },
  OrBezalel: { name: 'אור', fullName: 'Or Bezalel', phone: '0525393002', lang: 'he', form: 'm' },
  TamirTzarfati: { name: 'צרפתי וכינר', fullName: 'Tamir Tzarfati', phone: '0527799833', lang: 'he', form: 'plural' },
  RoiDuani: { name: 'דואני', fullName: 'Roi Duani', phone: '0542205228', lang: 'he', form: 'm' },
  AmirTuboul: { name: 'אמיר ובראל', fullName: 'Amir Tuboul', phone: '0524799997', lang: 'he', form: 'plural' },
  ItamarShahar: { name: 'איתמר והדס', fullName: 'Itamar Shahar', phone: '0542557288', lang: 'he', form: 'plural' },
  ItamarRosenshine: { name: 'איתמר ושיר', fullName: 'Itamar Rosenshine', phone: '0507722032', lang: 'he', form: 'plural' },
  StavBenShahar: { name: 'סטיב', fullName: 'Stav Ben Shahar', phone: '0528023652', lang: 'he', form: 'm' },
  IdanTopper: { name: 'טופר', fullName: 'Idan Topper', phone: '0523733779', lang: 'he', form: 'm' },
  ItamarLevyRinski: { name: 'איתמר הסטרייט ודנה', fullName: 'Itamar Levy Rinski', phone: '0502466646', lang: 'he', form: 'plural' },
  TamarTuboul: { name: 'תמר', fullName: 'Tamar Tuboul', phone: '0544903227', lang: 'he', form: 'f' },
  YanayTuboul: { name: 'ינאי', fullName: 'Yanay Tuboul', phone: '0547805805', lang: 'he', form: 'm' },
  MaayanKeren: { name: 'מעיין', fullName: 'Maayan Keren', phone: '0542677501', lang: 'he', form: 'm' },
  OmerKishoni: { name: 'עומר קיש', fullName: 'Omer Kishoni', phone: '0545910015', lang: 'he', form: 'm' },
  ItaySnapier: { name: 'איתי', fullName: 'Itay Snapier', phone: '0522587843', lang: 'he', form: 'm' },
  GuyTurevich: { name: 'גיא', fullName: 'Guy Turevich', phone: '0587050587', lang: 'he', form: 'm' },
  OrenEyal: { name: 'אורן', fullName: 'Oren Eyal', phone: '0543042321', lang: 'he', form: 'm' },
  KerenWix: { name: 'קרן', fullName: 'Keren Wix', phone: '0523827666', lang: 'he', form: 'f' },
  RotemAmazon: { name: 'רותם', fullName: 'Rotem Amazon', phone: '0526557003', lang: 'he', form: 'f' },
  YoavAmazon: { name: 'יואב', fullName: 'Yoav Amazon', phone: '0544966717', lang: 'he', form: 'm' },
  NoaAlmog: { name: 'נועה', fullName: 'Noa Almog', phone: '0547713201', lang: 'he', form: 'f' },
  TalSegal: { name: 'טל', fullName: 'Tal Segal', phone: '0545213156', lang: 'he', form: 'f' },
  ItayAmazon: { name: 'איתי', fullName: 'Itay Amazon', phone: '0543333491', lang: 'he', form: 'm' },
  YaronAmazon: { name: 'ירון', fullName: 'Yaron Amazon', phone: '0525226310', lang: 'he', form: 'm' },
  OdedFogel: { name: 'עודד', fullName: 'Oded Fogel', phone: '0549276202', lang: 'he', form: 'm' },
  MayaSharon: { name: 'מיה ואלון', fullName: 'Maya Sharon', phone: '0527889483', lang: 'he', form: 'plural' },
  NadavShoham: { name: 'נדב', fullName: 'Nadav Shoham', phone: '0542003355', lang: 'he', form: 'm' },
  OhadKlein: { name: 'אוהד', fullName: 'Ohad Klein', phone: '0526605068', lang: 'he', form: 'm' },
  ItsikLevi: { name: 'איציק', fullName: 'Itsik Levi', phone: '0542242257', lang: 'he', form: 'm' },
  RomMaltser: { name: 'רום', fullName: 'Rom Maltser', phone: '0528767919', lang: 'he', form: 'm' },
  GiladWasserman: { name: 'גלעד', fullName: 'Gilad Wasserman', phone: '0523409051', lang: 'he', form: 'm' },
  ChaimRand: { name: 'חיים', fullName: 'Chaim Rand', phone: '0547887184', lang: 'he', form: 'm' },
  YaelWolff: { name: 'יעל', fullName: 'Yael Wolff', phone: '0504803302', lang: 'he', form: 'f' },
  LironGrinstein: { name: 'לירון', fullName: 'Liron Grinstein', phone: '0503758950', lang: 'he', form: 'f' },
  TzviStrauss: { name: 'צבי', fullName: 'Tzvi Strauss', phone: '0509414949', lang: 'he', form: 'm' },
  RachelBarDin: { name: 'רייצ׳ל', fullName: 'Rachel Bar Din', phone: '0529457029', lang: 'he', form: 'f' },
  RotemFirstater: { name: 'רותם', fullName: 'Rotem Firstater', phone: '0546962760', lang: 'he', form: 'f' },
  GalGetz: { name: 'גל ועמית', fullName: 'Gal Getz', phone: '0542080686', lang: 'he', form: 'plural' },
  KerrenEli: { name: 'קרן', fullName: 'Kerren Eli', phone: '+31613224264', lang: 'he', form: 'f' },
  DanaMashevich: { name: 'דנה ואלמוג', fullName: 'Dana Mashevich', phone: '0528014889', lang: 'he', form: 'plural' },
  MichelleFishman: { name: 'מישל ואשל', fullName: 'Michelle Fishman', phone: '0547603705', lang: 'he', form: 'plural' },
  YuvalNetanel: { name: 'יובל', fullName: 'Yuval Netanel', phone: '0544956033', lang: 'he', form: 'm' },
  TalTzeelon: { name: 'טל', fullName: 'Tal Tzeelon', phone: '0543339742', lang: 'he', form: 'm' },
  JonathanKimelfeld: { name: 'קימל', fullName: 'Jonathan Kimelfeld', phone: '0526849924', lang: 'he', form: 'm' },
  MayaInbal: { name: 'מיה', fullName: 'Maya Inbal', phone: '0526418184', lang: 'he', form: 'f' },
  BarWeiner: { name: 'בר', fullName: 'Bar Weiner', phone: '0543290706', lang: 'he', form: 'm' },
  ElaWeiner: { name: 'ללי', fullName: 'Ela Weiner', phone: '0522773500', lang: 'he', form: 'f' },
  ItayLevinson: { name: 'לוינזון וליאור', fullName: 'Itay Levinson', phone: '0525870686', lang: 'he', form: 'plural' },
  YaronTiano: { name: 'ירון', fullName: 'Yaron Tiano', phone: '0528594191', lang: 'he', form: 'm' },
  MatanZano: { name: 'זנו', fullName: 'Matan Zano', phone: '0545696396', lang: 'he', form: 'm' },
  MosheZilberman: { name: 'משה', fullName: 'Moshe Zilberman', phone: '0546195509', lang: 'he', form: 'm' },
  ItzikCohen: { name: 'איציק', fullName: 'Itzik Cohen', phone: '0542559744', lang: 'he', form: 'm' },
  EdenIsraeli: { name: 'עדן', fullName: 'Eden Israeli', phone: '0545920387', lang: 'he', form: 'f' },
  DrorAvizrat: { name: 'דרור', fullName: 'Dror Avizrat', phone: '0549876583', lang: 'he', form: 'm' },
  Rafa: { name: 'רפא', fullName: 'Rafa', phone: '0535244303', lang: 'he', form: 'm' },
  ZoharHazani: { name: 'זוהר', fullName: 'Zohar Hazani', phone: '0544750400', lang: 'he', form: 'f' },
  MayAmazon: { name: 'מאי', fullName: 'May Amazon', phone: '0545422005', lang: 'he', form: 'f' },
  MayaKedmi: { name: 'מאיה', fullName: 'Maya Kedmi', phone: '0509888803', lang: 'he', form: 'f' },

  // --- Added from contacts.docx (2026-08-10) ---
  DanielObo: { name: 'אובו', fullName: 'Daniel Obo', phone: '0546964417', lang: 'he', form: 'm' },
  VladimirKofman: { name: 'וובה', fullName: 'Vladimir Kofman', phone: '0547350018', lang: 'he', form: 'm' },
  GalinaKasharovski: { name: 'גלינה ולאוניד', fullName: 'Galina Kasharovski', phone: '0508641333', lang: 'he', form: 'plural' },
  AmirZevin: { name: 'אמיר', fullName: 'Amir Zevin', phone: '0525284418', lang: 'he', form: 'm' },

  // --- Dvir's parents (2026-08-10) ---
  EliezerYuniov: { name: 'סבא ורותי', fullName: 'Eliezer Yuniov', phone: '0505437668', lang: 'he', form: 'plural' },
  OritHapiloni: { name: 'אורית ואייל', fullName: 'Orit Hapiloni', phone: '0502571156', lang: 'he', form: 'plural' },
  OritDan: { name: 'אורית ואילן', fullName: 'Orit Dan', phone: '0544998946', lang: 'he', form: 'plural' },
  OrenSasson: { name: 'אורן ואורה', fullName: 'Oren Sasson', phone: '0529597970', lang: 'he', form: 'plural' },
  EyalOzri: { name: 'אייל וסיגי', fullName: 'Eyal Ozri', phone: '0545642373', lang: 'he', form: 'plural' },
  IlanitShani: { name: 'אילנית ויובל', fullName: 'Ilanit Shani', phone: '0528665494', lang: 'he', form: 'plural' },
  SaharSasson: { name: 'סהר ומאור', fullName: 'Sahar Sasson', phone: '0523806067', lang: 'he', form: 'plural' },
  IrisCohenTzedek: { name: 'איריס ועופר', fullName: 'Iris Cohen Tzedek', phone: '0522946465', lang: 'he', form: 'plural' },
  EfratLang: { name: 'אפרת והילדים', fullName: 'Efrat Lang', phone: '0509508363', lang: 'he', form: 'plural' },
  EinatBrodetsky: { name: 'עינת וגיא', fullName: 'Einat Brodetsky', phone: '0549800491', lang: 'he', form: 'plural' },
  DotanSasson: { name: 'דותן וזהבה', fullName: 'Dotan Sasson', phone: '0542201220', lang: 'he', form: 'plural' },
  SaraBracha: { name: 'שרה ודניאל', fullName: 'Sara Bracha', phone: '0525408186', lang: 'he', form: 'plural' },
  KerenYuniov: { name: 'קרן וליאור', fullName: 'Keren Yuniov', phone: '0526231716', lang: 'he', form: 'plural' },
  HanochYuniov: { name: 'חנוך ומיכל', fullName: 'Hanoch Yuniov', phone: '0546175859', lang: 'he', form: 'plural' },
  RonBenDahan: { name: 'רון וגולן', fullName: 'Ron Ben Dahan', phone: '0538291457', lang: 'he', form: 'plural' },
  YafaBenYehuda: { name: 'יפה ומיכאל', fullName: 'Yafa Ben Yehuda', phone: '0544443185', lang: 'he', form: 'plural' },
  ShukiSasson: { name: 'שוקי וריקי', fullName: 'Shuki Sasson', phone: '0524265220', lang: 'he', form: 'plural' },
  MalkaSasson: { name: 'מלכה וצ׳פי', fullName: 'Malka Sasson', phone: '0542201103', lang: 'he', form: 'plural' },
  MaayanCohenGvura: { name: 'מעיין ונאור', fullName: 'Maayan Cohen Gvura', phone: '0545838364', lang: 'he', form: 'plural' },
  RotemBenYehuda: { name: 'רותם ומיטל', fullName: 'Rotem Ben Yehuda', phone: '0544443120', lang: 'he', form: 'plural' },
  ReutHai: { name: 'רעות ורועי', fullName: 'Reut Hai', phone: '0506819399', lang: 'he', form: 'plural' },
  DavidSasson: { name: 'דיוויד והדס', fullName: 'David Sasson', phone: '0507693429', lang: 'he', form: 'plural' },
  ShaniBenYehuda: { name: 'שני', fullName: 'Shani Ben Yehuda', phone: '0506532096', lang: 'he', form: 'f' },
  RivkaEliyahu: { name: 'רבקה ואשר', fullName: 'Rivka Eliyahu', phone: '0539647538', lang: 'he', form: 'plural' },
  AlmogYuniov: { name: 'אלמוג וסטפני', fullName: 'Almog Yuniov', phone: '0547758846', lang: 'he', form: 'plural' },
  NoamYuniov: { name: 'נועם', fullName: 'Noam Yuniov', phone: '0544939438', lang: 'he', form: 'm' },
  ShaharYuniov: { name: 'שחר', fullName: 'Shahar Yuniov', phone: '0546172760', lang: 'he', form: 'm' },
  BoazAmraz: { name: 'בועז', fullName: 'Boaz Amraz', phone: '0526031416', lang: 'he', form: 'm' },
  RonenAmraz: { name: 'רונן', fullName: 'Ronen Amraz', phone: '0526031389', lang: 'he', form: 'm' },
  IrenaAmraz: { name: 'אירנה', fullName: 'Irena Amraz', phone: '0526031482', lang: 'he', form: 'f' },
  RoniAmraz: { name: 'רוני', fullName: 'Roni Amraz', phone: '0528838658', lang: 'he', form: 'm' },
  LeonidAmraz: { name: 'לאוניד', fullName: 'Leonid Amraz', phone: '0526031432', lang: 'he', form: 'm' },
  AlfredAmraz: { name: 'אלפרד', fullName: 'Alfred Amraz', phone: '0526031441', lang: 'he', form: 'm' },
  YanivAmraz: { name: 'יניב', fullName: 'Yaniv Amraz', phone: '0543948046', lang: 'he', form: 'm' },
  IrisSaiby: { name: 'איריס', fullName: 'Iris Saiby', phone: '0522303639', lang: 'he', form: 'f' },
  HilikAmraz: { name: 'חיליק', fullName: 'Hilik Amraz', phone: '0526031474', lang: 'he', form: 'm' },
  HaimMoskovitz: { name: 'חיים', fullName: 'Haim Moskovitz', phone: '0526031312', lang: 'he', form: 'm' },
  LiadAmraz: { name: 'ליעד', fullName: 'Liad Amraz', phone: '0526031374', lang: 'he', form: 'm' },
  YaakovAmraz: { name: 'יעקב', fullName: 'Yaakov Amraz', phone: '0526031471', lang: 'he', form: 'm' },
  MeitalAmraz: { name: 'מיטל', fullName: 'Meital Amraz', phone: '0526222812', lang: 'he', form: 'f' },
  AviNayek: { name: 'אבי', fullName: 'Avi Nayek', phone: '0526031317', lang: 'he', form: 'm' },
  ItzikAmraz: { name: 'איציק', fullName: 'Itzik Amraz', phone: '0524349417', lang: 'he', form: 'm' },
  DavidSalman: { name: 'דוד', fullName: 'David Salman', phone: '0526031314', lang: 'he', form: 'm' },
  EtiAmraz: { name: 'אתי', fullName: 'Eti Amraz', phone: '0526031408', lang: 'he', form: 'f' },
  GabiAmraz: { name: 'גבי', fullName: 'Gabi Amraz', phone: '0539883927', lang: 'he', form: 'm' },
  MichalKreshberg: { name: 'מיכל ומיקו', fullName: 'Michal Kreshberg', phone: '+32485616831', lang: 'he', form: 'plural' },
  MarkItay: { name: 'מארק', fullName: 'Mark Itay', phone: '0524633349', lang: 'he', form: 'm' },
};

const VALID_LANGS = ['he', 'en', 'ru'];

export function resolveGuest(search) {
  const params = new URLSearchParams(search != null ? search : '');

  const code = params.get('g');
  if (code && GUESTS[code]) {
    const g = GUESTS[code];
    return { code, ...g, fullName: g.fullName || g.name };
  }

  const legacyLang = params.get('lang');
  const to = params.get('to') || undefined;
  return {
    code: params.get('id') || null,
    name: to,
    fullName: to,
    phone: undefined,
    lang: VALID_LANGS.includes(legacyLang) ? legacyLang : undefined,
    form: undefined,
  };
}

export { GUESTS };
